FROM resin/rpi-raspbian:latest
#FROM armhf/alpine:latest

WORKDIR /root/

EXPOSE 25565
EXPOSE 8080

ADD https://builds.cuberite.org/job/Cuberite%20Linux%20raspi-armhf%20Master/lastSuccessfulBuild/artifact/Cuberite.tar.gz ./ 

COPY Server .

CMD ["/root/Server/Cuberite"]